openapi: 3.0.0
info:
  title: Person and Goals API
  description: API to manage persons, their contacts, goals, and grades.
  version: "1.0.0"
servers:
  - url: http://localhost:8000
    description: Local development server
paths:
  /person/contact-persons/{person_id}:
    get:
      summary: Retrieve contact persons for a given person.
      description: Returns a list of contact persons related to the provided person ID.
      operationId: get_contact_persons
      parameters:
        - name: person_id
          in: path
          required: true
          description: ID of the person to retrieve contact persons for.
          schema:
            type: string
      responses:
        '200':
          description: A list of contact persons.
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true

  /person/students/:
    get:
      summary: Retrieve all students.
      description: Returns a list of students.
      operationId: get_contacts
      responses:
        '200':
          description: A list of students.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  additionalProperties: true

  /person/students/radar-chart/{person_id}:
    get:
      summary: Retrieve radar chart data for a specific student.
      description: Returns radar chart data based on a person's ID.
      operationId: get_radar_chart_data
      parameters:
        - name: person_id
          in: path
          required: true
          description: ID of the person to retrieve radar chart data for.
          schema:
            type: string
      responses:
        '200':
          description: Radar chart data for the specified person.
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true

  /goals/:
    post:
      summary: Create a new goal.
      description: Accepts a JSON request body with goal data to create a new goal.
      operationId: post_goal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        '200':
          description: The created goal data.
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true

  /goals/{person_id}:
    get:
      summary: Retrieve goals for a specific person.
      description: Returns
