openapi: 3.0.0
info:
  title: Contact and Student API
  description: API to retrieve student contact details, goals, and grades.
  version: 1.0.0
  contact:
    name: Mathis Heldner
    email: mathis.heldner@bluewin.ch
servers:
  - url: http://localhost:8000
    description: Local Development Server
paths:
  /contact-persons/{person_id}:
    get:
      summary: Get contact persons of a specific apprentice
      description: Retrieve the contact persons for a given apprentice using their `person_id`.
      parameters:
        - name: person_id
          in: path
          required: true
          schema:
            type: string
          description: The unique ID of the apprentice for whom we want the contact persons.
      responses:
        '200':
          description: Successfully retrieved the contact information.
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Person not found.
        '500':
          description: Internal server error.

  /students/:
    get:
      summary: Get list of all students
      description: Retrieve a list of all registered students.
      responses:
        '200':
          description: A list of students.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '500':
          description: Internal server error.

  /goals/{person_id}:
    get:
      summary: Get goals of a specific apprentice
      description: Retrieve the goals of a specific apprentice identified by their `person_id`.
      parameters:
        - name: person_id
          in: path
          required: true
          schema:
            type: string
          description: The unique ID of the apprentice to retrieve goals for.
      responses:
        '200':
          description: Successfully retrieved goals for the person.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '404':
          description: Goals not found for the specified apprentice.
        '500':
          description: Internal server error.

  /grades/{person_id}:
    get:
      summary: Get grades of a specific apprentice
      description: Retrieve the grades of a specific apprentice identified by their `person_id`.
      parameters:
        - name: person_id
          in: path
          required: true
          schema:
            type: string
          description: The unique ID of the apprentice to retrieve grades for.
      responses:
        '200':
          description: Successfully retrieved grades for the person.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '404':
          description: Grades not found for the specified person.
        '500':
          description: Internal server error.

components:
  schemas:
    Goal:
      type: object
      properties:
        goal_id:
          type: string
        description:
          type: string
        created_at:
          type: string
          format: date-time
        due_date:
          type: string
          format: date
        goal_type:
          type: string
        status:
          type: string

    Grade:
      type: object
      properties:
        subject:
          type: string
        grade:
          type: string
        created_at:
          type: string
          format: date-time
